name: Deploy

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup Odin and LLVM
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: latest

      - name: Build Web
        run: make release-web

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: bin/web

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    permissions:
      pages:    write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
